### ISSUE TITLE
[Give 2.2.0] Update: payment meta table related docs

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp-docs#171]
## Description
To prevent conflict with Restrict Content Pro plugin we renamed payment meta table. Maybe we mentioned table somewhere in the doc (code snippet )., so It will good we scan our docs and update them.

**Issue Link:** https://github.com/WordImpress/Give/issues/2710#issuecomment-377852730

**Comment by mathetos** [comment]
We have had some developer-users request a full database schema for Give. I think something like that would be useful in developer docs. 

@ravinderk is that something you can provide relatively easily?
@kevinwhoffman do you have thoughts on that at all?

**Comment by kevinwhoffman** [comment]
We could use the Codex example of the WP database as a blueprint for our Give documentation. I think a database diagram coupled with an explanatory table works well.

- [Database Diagram](https://codex.wordpress.org/Database_Description#Database_Diagram)
- [Table Overview](https://codex.wordpress.org/Database_Description#Table_Overview)

I believe [MySQL Workbench](https://www.mysql.com/products/workbench/) was used to generate a visual model of the database as seen here. We should be able to hook up a local install of Give to generate the model.

Here is a [Video Demo of MySQL Workbench](https://youtu.be/X_umYKqKaF0?t=461
) being used to generate the diagram.

**Comment by allienimmons** [comment]
@DevinWalker @mathetos This has not been touched for 6 months. Is this something we are still prioritizing?

**Comment by DevinWalker** [comment]
We are not prioritizing this so I'm closing as our database schema will be changing even more in future iterations.
