### ISSUE TITLE
web-doc: update 2checkout add-on and documentation page.

### ISSUE THREAD

**Issue by marutim** [impress-org/givewp-docs#211]
## Issue Info
* Docs URL:https://givewp.com/addons/2checkout-gateway/ https://givewp.com/documentation/add-ons/2checkout-gateway/
* Issue Type: Update

## Issue Description

Due to the recent change in Policy, 2checkout does not allow donations for NGO outside of the US. Please make the necessary changes in the add-on and documentation ( and probably in the countries page ) to make this clearer to the customer.

## Related Issues
https://github.com/impress-org/give-2checkout/issues/52
https://secure.helpscout.net/conversation/799697461/35882/

## Acceptance Criteria

**This doc is ready to publish when:**
- [ ] I see an updated add-on and documentation page that makes it clear to the users that this payment gateway can only be now used in the US to accept donations.

**Comment by allienimmons** [comment]
Draft here: https://docs.google.com/document/d/195FGseqr3AGXrqgsDPVQMopjsS8m2X4SVIzLvafaCmk/edit#

**Comment by allienimmons** [comment]
@mathetos Please review and provide feedback!

**Comment by allienimmons** [comment]
@mathetos Pinging again to ask you to look at the draft linked above

**Comment by mathetos** [comment]
@allienimmons Draft is good to go. Feel free to close it out once the doc is updated. Thanks!
