### ISSUE TITLE
web-doc: add recurring donations for mollie doc

### ISSUE THREAD

**Issue by mathetos** [impress-org/givewp-docs#212]
## Issue Info
* Docs URL: https://givewp.com/documentation/add-ons/recurring-donations/supported-payment-gateways/mollie
* Doc Title: Recurring Donations with the Mollie Payment Gateway
* Issue Type: New

## Issue Description

We need to add this doc to the "Supported Payment Gateways" section of Recurring Donations. 

## Acceptance Criteria

**This doc is ready to publish when:**
- [ ] The doc is created with 
    - [ ] an intro
    - [ ] list of requirements
    - [ ] a walkthrough
    - [ ] relevant screenshots
    - [ ] relevant links to related docs like Testing Mode, Mollie docs, general Recurring docs
- [ ] By the end of the article, users understand completely how to configure Give for recurring donations with Mollie

**Comment by mathetos** [comment]
@samsmith89 Please do the following:
1. Start a Google Doc in a FOLDER in Drive with a detailed outline of what this needs, use my list above as a guide as well as the [PayPal Standard](https://givewp.com/documentation/add-ons/recurring-donations/supported-payment-gateways/paypal-standard/) doc since I think they'll be similar. 
2. In that same FOLDER add all relevant screenshots as as high a resolution as you can get them. 

Update here when those are done and I'll take it from there. Thanks!

**Comment by samsmith89** [comment]
@mathetos there isn't going to be much for this doc as there isn't any setup I can find. It just works when recurring is enabled. I added more information in the doc.

Here is the link to the folder in Drive:
https://drive.google.com/open?id=1-1QeYHaHpNROk1fghDsEh_ii60RayOhc

Here is the link to the doc:
https://docs.google.com/document/d/1HGKvX8W_hD8wJ8Yp4FtYcl17cJuphSN5SMj6r_cH24M/edit?usp=sharing

**Comment by Benunc** [comment]
done. https://givewp.com/documentation/add-ons/recurring-donations/supported-payment-gateways/mollie/
