### ISSUE TITLE
web-doc: add resource doc on how to merge donors

### ISSUE THREAD

**Issue by mathetos** [impress-org/givewp-docs#221]
## Issue Info
* Docs URL: https://givewp.com/documentation/resources/how-to-merge-donors
* Doc Title: How to Merge Donors
* Issue Type: New

## Issue Description

We need a doc that walks users through how to merge donors and all the caveats to that process.

## Acceptance Criteria

This is the outline:

- [x] 1. Introduce the problem
- [x] 2. Transition to explain it’s different whether the donors have users or not, and whether they have Subscriptions or not
- [x] 3. Merging Two Donors where BOTH have Subscriptions is not supported
- [x] 4. Merging Two Donors where ONE has a Subscription
- [x] 5. Merging Two Donors that only have one-time Donations

Draft is started here:
https://docs.google.com/document/d/1yKZ4ilGTW70gEflwzSsoInyJMXJqEmbfB3iwPs7CedY/edit#

Folder for all assets:
https://drive.google.com/drive/folders/1YwHGr9-jjVnoecbw_HSmgNnbHSS_gmdW

**Comment by allienimmons** [comment]
Refreshing this reminder for @Benunc or @mathetos to give this a glance please.

**Comment by mathetos** [comment]
Great work. Publishing for now after a short review. Let's revisit after we send a few users to it and see how well it works for them.
