### ISSUE TITLE
web-doc: update Recurring Form Fields to mention recurring subscribers as a goal

### ISSUE THREAD

**Issue by mathetos** [impress-org/givewp-docs#226]
## Issue Info
* Docs URL: https://givewp.com/documentation/add-ons/recurring-donations/recurring-donation-forms/
* Issue Type: Update

## Issue Description

When recurring is enabled, the goal has the option to be limited only to recurring donations. That is not currently documented and needs to be. 

We also need to clarify the following:
- Do renewals increase the progress amount?
- If "Number of Donations" is chosen, do the renewals increase the progress amount?

## Assets

![image](https://user-images.githubusercontent.com/930724/61967973-a1b7c100-af8b-11e9-8e30-1244f484c4b4.png)

## Acceptance Criteria

- [ ] A new section called "Recurring Goals" is added
- [ ] The new section clarifies what happens when the goals is enabled
    - [ ] Specifically how the goals progress in relation to renewals
    - [ ] Specifically what happens when "Number of Donations" is chosen in relation to renewals

**Comment by stephaniehellwig** [comment]
Compare current docs with add-on behavior to write the acceptance criteria> assign for completion.

**Comment by Benunc** [comment]
Amount : $200 out of $500 (only counts subscription value)
Percentage: 41% raised (only counts subscription value)
Donations: counts the total number of active subscriptions. (lists as "donations")
Donors: total active subscriptions (lists as "donors")

**Comment by Benunc** [comment]
This is done. See the final section here: https://givewp.com/documentation/add-ons/recurring-donations/recurring-donation-forms/

Comments and corrections welcomed.
