### ISSUE TITLE
web-doc: update Square doc to include how to link Square to Give via API

### ISSUE THREAD

**Issue by stephaniehellwig** [impress-org/givewp-docs#228]
## Issue Info
* Docs URL: https://givewp.com/documentation/add-ons/square-gateway/

* Issue Type: Update

## Issue Description
The current Square docs do not mention that there is another way to link Give with Square. 
 We need to show how to use the API method to link Square to Give

## Assets
https://drive.google.com/open?id=1a4Md716jIFB7CAwsWi5JZG_xWvMXF7DQ

## Acceptance Criteria

**This doc is ready to publish when:**
- [ ] I see a new section in the doc for the API method
- [x] I understand how to link Give with Square using the API method
- [x] I see any necessary graphics or screenshots to demonstrate the process

**Comment by stephaniehellwig** [comment]
https://squareup.com/us/en/developers > developer dashboard
Create an app to get the API keys

**Comment by stephaniehellwig** [comment]
Ticket for refrence: https://secure.helpscout.net/conversation/943601646/46148?folderId=2805787

**Comment by allienimmons** [comment]
@mathetos  This draft is ready for review.  Once I have access to Figma, I definitely want to re-do the screenshots to not have red arrows, but those screenshots are indicative of placement and content. https://docs.google.com/document/d/1PjAQCdGrX0lE7v8lk28YeSohuwtL3hTufCdk0FQmWtA/edit
