### ISSUE TITLE
web-doc: Dashboard link is broken

### ISSUE THREAD

**Issue by michelleames** [impress-org/givewp-docs#231]
![Screen Shot 2019-08-29 at 10 26 24 AM](https://user-images.githubusercontent.com/14227933/63949702-cbf81500-ca48-11e9-8807-a749bdc6a86a.png)

The link for webbooks documentation in the dashboard for Stripe returns at http://docs.givewp.com/  (There is an extra space at the end of the link that is resulting in the dead page.)

(Reported to me for an NGO site I'm helping with on my vacation.)

**Comment by allienimmons** [comment]
@mikejhale What is the status on this?

**Comment by mathetos** [comment]
@allienimmons The patch has been merged, it's being released in GiveWP `2.5.9`

See here:
https://github.com/impress-org/givewp/issues/4266
