### ISSUE TITLE
web-doc: update Advanced setting to indicate the stripe and square options

### ISSUE THREAD

**Issue by stephaniehellwig** [impress-org/givewp-docs#232]
## Issue Info
* Docs URL: https://givewp.com/documentation/core/settings/advanced/
* Docs URL: https://givewp.com/documentation/add-ons/stripe-gateway/
* Docs URL: https://givewp.com/documentation/add-ons/square-gateway/

* Issue Type: Update

## Issue Description
There is not currently anywhere in the docs that indicate the Stripe or Square settings in the Donations > Settings > Advanced  tab
There may be other payment gateways that also add settings here and those will need to be added here as well.

## Acceptance Criteria

**This doc is ready to publish when:**
- [x] I see mention of the Stripe and Square settings available in the advanced tab
- [x] I see mention on the Stripe docs of the advanced tab settings
- [x] I see mention on the Square docs of the advanced tab settings
- [x] I understand that there are options in the advanced tab for some of the payment gateways and I see what they are for and how to use them
- [x] the formatting of the explanation for those fields follows the formatting here: https://givewp.com/documentation/core/settings/emails/ (settings type, options, default, explanation)

**Comment by Benunc** [comment]
Start with adding a section to the add-on docs for the advanced settings. Then we can decide if and how we want to link to those sections on the core advanced settings doc.

**Comment by allienimmons** [comment]
Rough draft for Stripe and Square advanced tabs: https://docs.google.com/document/d/1S86Sq3yBur5BuIndLHW2Q-jCK9NzzVq_THEvUVlco2s/edit#

**Comment by Benunc** [comment]
I made comments on that draft @allienimmons  

Very well done. 

Make those changes, and then go ahead and publish this one on the site. Ping here for a review once it's live on the site.

**Comment by allienimmons** [comment]
@Benunc The page for the Stripe settings is published.  https://givewp.com/documentation/core/settings/advanced/stripe/

**Comment by Benunc** [comment]
I thought these were going to be added to the Stripe Doc and the Square doc, not as standalone pages. @mathetos thoughts?

I like having them as separate pages for the structure of the docs, but I also know that (1) we are working toward fewer and longer docs and (2) in the future the advanced tab is not going to have these sections.

I think that for those two reasons we should make these two docs sections on 
https://givewp.com/documentation/add-ons/stripe-gateway/
and
https://givewp.com/documentation/add-ons/square-gateway/
respectively.

**Comment by mathetos** [comment]
Ya in this case folks aren't going to be looking for these settings in the traditional settings screen navigation way. They're just going to want to know these settings exist, so let's consolidate them to the individual addon doc pages and delete these with a redirect.

**Comment by allienimmons** [comment]
If I'm understanding correctly, as an example, we'd want the Stripe page to appear in this list, with a page title like "Advanced Settings"
<img width="813" alt="Screen Shot 2019-09-18 at 9 14 36 AM" src="https://user-images.githubusercontent.com/41754561/65151811-d3319380-d9f4-11e9-8b86-2cbb0f7d474c.png">

**Comment by Benunc** [comment]
No, as a section at the bottom of that page. 

![Screen Shot 2019-09-18 at 9 41 42 AM](https://user-images.githubusercontent.com/9629102/65153947-a2ebf400-d9f8-11e9-87c2-ab1438c6b449.png)

**Comment by allienimmons** [comment]
Updated the following 2 links with this new content:

https://givewp.com/documentation/add-ons/stripe-gateway/
https://givewp.com/documentation/add-ons/square-gateway/

**Comment by Benunc** [comment]
Make a simple note at the top of each new section that says 
> Some settings for {gateway name} are located in the Advanced tab at Donations > Settings > Advanced > {gateway}. This section covers those settings and options. 

Once you do that, close this WITH AUTHORITY. :-)

**Comment by allienimmons** [comment]
Matt suggested closing the other 2 docs I made with redirects. How do I go about that?

**Comment by Benunc** [comment]
@mathetos will need to do that.

**Comment by mathetos** [comment]
Old posts deleted and 301 redirected successfully. Thanks all!
