### ISSUE TITLE
web-doc: update Custom Functions to include syntax/formatting instructions

### ISSUE THREAD

**Issue by allienimmons** [impress-org/givewp-docs#233]
## Issue Info
* Docs URL: https://givewp.com/documentation/resources/adding-custom-functions-to-your-wordpress-website/
* Issue Type: Update

## Issue Description
Many users do not understand intuitively to remove the <?php from the beginning of a snippet prior to adding it to My Custom Functions. They also may not know that you cannot add one snippet after the other without skipping lines. The update should include either a screenshot or screencast of someone copy/pasting multiple php snippets into a WordPress site, omitting the <?php and making sure to add a line break between the two.

## Assets
Should we use a screenshot or screencast? 

## Acceptance Criteria

**This doc is ready to publish when:**
- [x] I see a reference to <?php needing to be omitted from copy/pasting
- [x] I see a visual representation of moving the snippet from the repo to the site without <?php
- [x] I see an example of adding more than one snippet, separated by a line break.

**Comment by allienimmons** [comment]
@stephaniehellwig Please review!

**Comment by Benunc** [comment]
A screencast would likely be overkill for this. I think screenshots and text will suffice. I'd make the change directly on the site, no need for a rough draft.

**Comment by allienimmons** [comment]
Doc with suggested edits: https://docs.google.com/document/d/1V79UaJakhzHOmRnoMIHMTnLaYJFWGkzbpRKZKkfvv3c/edit

**Comment by Benunc** [comment]
I made suggestions on the google doc. go ahead and add the changes to the doc, and ping again here for me to read over it and close this. great work.

**Comment by allienimmons** [comment]
Added to the doc: https://givewp.com/documentation/resources/adding-custom-functions-to-your-wordpress-website/
