### ISSUE TITLE
update: Stripe screenshots for new Settings UI and general improvements

### ISSUE THREAD

**Issue by mathetos** [impress-org/givewp-docs#235]
## Issue Info
* Docs URL: https://givewp.com/documentation/add-ons/stripe-gateway/
* Docs URL: https://givewp.com/documentation/core/payment-gateways/stripe-free/ 
* Issue Type: Update

## Issue Description

Give Stripe version 2.2.1 will bring a new settings UI allowing a third tab. 

Additionally, the current screenshots, particularly on Stripe Premium are a bit of an eyesore. Let's ramp them all up

## Screenshot Guidance

Here's tips for awesome screenshots:
1. Try to do as much of the screen as possible or as helpful so the user has as much context as possible. Also because we want these screenshots to fill the width of the content area as much as possible.
2. make sure there are only 1-2 arrows on the screen at a time
3. Arrows should always be exactly vertical or horizontal, never angled
4. Arrows should always be in our Give Green HEX = #68bb6c 
5. Ensure there's at least 10% "white space" around the image and the spacing is even on all sides.

## Screenshots that need updating:

*STRIPE PREMIUM*

- [x] "Connect to Stripe" -- doesn't need updating
- [x] Stripe Login screen -- Should not have Lastpass or any info in the fields at all
- [x] Give Connect Screen -- instead of blurring out the sensitive info, use Inspect Element to change the account names to something generic like "John Doe" or "john@example.org"
- [x] Give Settings in Stripe -- Update to reflect Stripe 2.1.1 new settings UI
- [x] Stripe Webhooks instructions -- Break this up into two screenshots. First is just the Webhook screen without the modal. Have ONE arrow to the "Add endpoint" button. Second screenshot is with the Modal open -- no arrows or highlights at all. The text should make this much more explicit in terms of what fields should have what info and that should be right below this screenshot.
- [x] Stripe API Keys Settings Screen -- New screenshot with new Settings UI. No Arrows.
- [x] "Obtaining your Stripe API Keys" FIRST -- this first screenshot is not necssary at all.
- [x] API Keys -- this should be a new screenshot. Don't blur the keys, these are TEST KEYS and can be regenerated without hiccup. 
- [x] Statement Descriptor -- Update this to be a larger screenshot of a sample donation so there's more context to what the Descriptor is. 
- [x] "Enable Stripe Checkout" -- Update to the new settings UI and make sure the use the GIVE icon for the Checkout image, not the WordPress fauxgo (eesh!)
- [x] Stripe Modal -- remove this screenshot for now
- [x] Stripe CC fields example screenshots. -- Update both of these to show more of the form for context and full-width. Preferrably from our Demos page (Matt/Devin might need to help make the single-line example work on the website locally)

*STRIPE FREE*
_This is a duplicate of the webhook in Stripe Premium, so once that's done, it's easy to update on Free as well._

- [x] Stripe Webhooks instructions -- Break this up into two screenshots. First is just the Webhook screen without the modal. Have ONE arrow to the "Add endpoint" button. Second screenshot is with the Modal open -- no arrows or highlights at all. The text should make this much more explicit in terms of what fields should have what info and that should be right below this screenshot.

## Acceptance Criteria
The checkboxes above are the acceptance criteria.

**Comment by allienimmons** [comment]
Please update this to include details on the Remember Me setting. What is it remembering? (names, emails, cc info, etc) Where is the info being stored (give vs stripe)

**Comment by mathetos** [comment]
Thanks @mikejhale for putting this together to help with the "Remember Me" settings. 

https://docs.google.com/document/d/15q8MHCVSqwylUaok-2zte5KzdqMnF_B4xzOXG6T6naQ/edit

**Comment by mathetos** [comment]
I've checked off the screenshots from the list above that I've already updated. There's quite a few more still to do, but it's good progress. The Figma workflow I think will be a good one for us.

**Comment by mathetos** [comment]
All screenshots have been updated, but doing this highlights that the settings descriptions are outdated compared to the new UI. Creating a new issue to address that.
