### ISSUE TITLE
chore: Document new Stripe Checkout 2.0 process

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp-docs#236]
@mikejhale commented on [Wed Jul 31 2019](https://github.com/impress-org/givewp/issues/4208)

## User Story

As a user I want clear documentation on how to configure Stripe Checkout 2.0 and the benefits of using it. 

## Possible Solution
Similar to https://docs.wpsimplepay.com/articles/new-stripe-checkout/ when it’s nearing release so our customers know how they can upgrade to the new checkout version

---

@mehul0810 commented on [Fri Aug 30 2019](https://github.com/impress-org/givewp/issues/4208#issuecomment-526578944)

**Update:**
Here are a couple more detailed documentation explaining how their plugins are implementing SCA:
- https://easydigitaldownloads.com/blog/strong-customer-authentication-is-coming/
- https://woocommerce.com/posts/introducing-strong-customer-authentication-sca/

**Comment by allienimmons** [comment]
@mathetos Is this something that has gotten any forward momentum?

**Comment by mathetos** [comment]
@allienimmons I missed this one somehow, and created this one instead and assigned it to you. I think mine describes the way we should implement this, so I'll close this in favor of mine:
https://github.com/impress-org/givewp-docs/issues/247
