### ISSUE TITLE
web-doc: update Managing Subscriptions to include creating existing subscriptions

### ISSUE THREAD

**Issue by allienimmons** [impress-org/givewp-docs#237]
## Issue Info
* Docs URL: https://givewp.com/documentation/add-ons/recurring-donations/managing-subscriptions/
* Issue Type: Update

## Issue Description
Update the doc to include more details and guidance on creating existing subscriptions with Stripe, based on Matt's response from the ticket below.

## Assets
https://secure.helpscout.net/conversation/965700270/47872?folderId=672194

## Acceptance Criteria

**This doc is ready to publish when:**
- [ ] I see a new section related to adding existing subscriptions.
- [ ] I understand how to add subscriptions the already exist in Stripe.
- [ ] I can see how to  troubleshoot 1 or 2 common problems with creating existing subscriptions.

**Comment by mathetos** [comment]
I ended up answering a ticket on this issue again today. I'd like to get this updated ASAP so we don't have to write this over and over again. 

Additionally, reference this to see if they way I worded this is a little better than the previous response:
https://secure.helpscout.net/conversation/997111777/50074/

**Comment by Benunc** [comment]
DONE. I may need to add a video of this, or a couple of screenshots, but it is LIVE.
