### ISSUE TITLE
web-doc: Update Zapier to touch on statuses for one-time and first-time donations

### ISSUE THREAD

**Issue by allienimmons** [impress-org/givewp-docs#238]
## Issue Info
* Docs URL: https://givewp.com/documentation/{issue}
* Doc Title: (only necessary if a new doc)
* Issue Type: Update|New|Reorder

## Issue Description
Update the doc to explain how to set up Zaps to send emails for only one-time donations or first-time subscriptions. Should focus on the published and complete statuses and their difference. Use the ticket below to build an example scenario with a walkthrough of what to look for and what is the expected behavior.

## Assets
https://secure.helpscout.net/conversation/965944022/47919/
https://secure.helpscout.net/conversation/923863192/44839/

## Acceptance Criteria

**This doc is ready to publish when:**
- [ ] I see screenshots of the Zapier-side of the action
- [ ] I understand what to look for when setting up this kind of Zap
- [ ] I understand how to test this Zap

**Comment by Benunc** [comment]
added an additional ticket here that can showcase how to get a sample donation that has ALL THE DATA in it for setup of a Zap: use manual donations.

**Comment by Benunc** [comment]
Done https://givewp.com/documentation/add-ons/zapier/
